### ISSUE TITLE
alpha -> beta、beta -> rc時にバージョンのカウントをリセットする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/release-manager-actions#13]
現状引き継がれるけどリセットしたい

**Comment by kakkokari-gtyih** [comment]
> Q: Why do rcs have continuation number of beta?
>
> A: To prevent conflict when going back from ready to draft

らしいけど https://github.com/misskey-dev/release-manager-actions/blob/v2/README.md

**Comment by syuilo** [comment]
readyからdraftに戻さないようにすればよさそう

**Comment by tamaina** [comment]
> readyからdraftに戻さないように

ヒューマンエラーは普通にあると思うしGitHub側では対策不可なので

過去のバージョン一覧を取得してカウントを続けるみたいなことはできるとは思いますが…正直手を抜いたところではある

**Comment by kakkokari-gtyih** [comment]
> 過去のバージョン一覧を取得してカウントを続けるみたいなことはできるとは思いますが…正直手を抜いたところではある

これが理想ではある（beta4でrc.0に上げてその後betaに戻したらbeta.5として出るみたいな…？）

**Comment by tamaina** [comment]
別にalpha/beta/rcが連続した番号でもさして問題ないかと思いこの仕様にしてしまった

**Comment by kakkokari-gtyih** [comment]
> 別にalpha/beta/rcが連続した番号でもさして問題ないかと思いこの仕様にしてしまった

実際問題は無いと思う（見た目が不思議になるだけ）

**Comment by tamaina** [comment]
というかalpha/betaの別を作った以上、rcがready for reviewと関連付いてる必要性薄い

**Comment by tamaina** [comment]
ていうか分離されてんだわもう

**Comment by tamaina** [comment]
（じゃあなんで番号続ける仕様を引き継いだ？

**Comment by tamaina** [comment]
なんかもう綺麗に全部自分でやりたいなら

1. variablesあたりでプレリリース記号のリストを用意しとく (例: `"alpha" "beta" "rc"`)
2. release-with-dispatchをフラグを立てて起動するとプレリリース記号リストの次が選択される 例: beta  → rc
   もし最後のものであってもフラグが立っていたら…何もしない？
3. release-with-readyは廃止する

ready for reviewでrcになる(release-with-ready)は飽くまでオートメーションに振った仕様にしたというころがあったので、別にそれがいらないならこういった仕様でも良さそう

**Comment by anatawa12** [comment]
とりあえず現行仕様からあまり大きく外れない範囲で改造した感じなのですごい理由があるわけでもない(breaking changesと画像の作成を避けた)

**Comment by anatawa12** [comment]
対処終わったのでunpin
